#!/usr/bin/perl

use strict;
use warnings;

use LWP::UserAgent;

my $ua	= LWP::UserAgent->new;
my $req	= HTTP::Request->new( GET => 'http://somafm.com' );
my $res = $ua->request($req);
my $seen;

my $header = <<'EOM';
                                 __                                
      ___  ___  _ __ ___   __ _ / _|_ __ ___    ___ ___  _ __ ___  
     / __|/ _ \| '_ ` _ \ / _` | |_| '_ ` _ \  / __/ _ \| '_ ` _ \ 
     \__ \ (_) | | | | | | (_| |  _| | | | | || (_| (_) | | | | | |
     |___/\___/|_| |_| |_|\__,_|_| |_| |_| |_(_)___\___/|_| |_| |_|

EOM
 
if ( $res->is_success ) {
	my @d = split /\n/, $res->decoded_content;
	my %stations;
	my $station = 10000;
	my ( $c, $n ) = 0;

	for ( @d ) {
		$c++;
		last if /<!-- End of stations -->/i;
		next unless ( $seen or /<!-- Start of Stations -->/i );
		$seen = 1;

		if ( /<a href/ ) {
			s/^.*"\///;
			s/\/".*$//;
			my $det		= $d[ $c ];
			my $des		= $d[ $c+2 ];
			$det		=~ s/(^.*alt="|".*$)//;
			(my $name, $det)= split /:/, $det;
			$det		=~ s/(^\s| commercial-free.*$)//g;
			$des		=~ s/(^.*">|<.*$)//g;
			$stations{ $_ }{ name }	= $name;
			$stations{ $_ }{ det }	= $det;
			$stations{ $_ }{ des }	= $des;
		}

	}

	print $header;

	map { 
		print "\t". $n++ .". $stations{ $_ }{ name } ($stations{ $_ }{ det })\n"
		    . "\t    - $stations{ $_ }{ des }\n\n"
	} sort keys %stations;

	print "\t0. Quit\n\n";

	while ( $station !~ /\d/ || $station < 0 || $station > keys %stations ) {
		print "Enter your choice (1-" . (keys %stations) . "): ";
		$station = <STDIN>;
		chomp $station;
	}

	print "Bye.\n" and exit if ( $station == 0 );
	my @urls = sort keys %stations;
	print "url is $urls[ $station ]\n";

	system "mplayer http://ice.somafm.com/$urls[ $station ]";
}
else {
	print "Unable to retrieve playlist: " . $res->status_line . "\n";
	exit;
}

